Settings:
  Prefix: '&7[&dEpicSellChest&7]: ' #The prefix before all messages from the plugin.
  Base-Price: 10 #The base price for the items being sold.
  Base-Currency: Vault #The base currency being used when selling items.
  Allow-Damaged-Items: true #Toggle if players can sell damaged items.
  Use-Two-Factor-Auth: true #Toggle if the player has to do the command again to confirm the sell.
  Custom-Currencies: #List of custom currencies that you can make. If you wish to not use them leave as it and just don't use it in the prices.
    Vault:
      Command: 'eco give %player% %cost%'
    Gold_Ingot:
      Command: 'give %player% goldingot %cost%'
  Chest-Selling-Item:
    Item: 'QUARTZ' #The item the chest selling item will be.
    Name: '&5&lEpic Selling Wand' #The name of the item.
    Lore: #The lore of the item.
      - '&7The Epic Selling Wand sells the'
      - '&7chest that you right click with it.'
      - ''
      - '&7&l(&4&l!&7&l) &7Right click a chest to sell it.'
    Glowing: true #If it has a glowing effect.
  Selling-Options:
    Price-Selling-Only: false #Sell only items that have a price.
  Region-Options: #All the options regarding regions.
    Max-Block-Area: 5000 #The max amount of blocks in the region a player can have.
    Chest-Sell-Toggle: true #Toggle if players have max chests that can be sold in a region.
    Max-Chest-Sell: 50 #The max amount of chests players can sell in a region. It ignores any chests that are empty or just have blacklisted items.
  Sign-Options:
    Toggle: true #Toggle if players can make signs. The player must have this permission: epicsellchest.sign
    Inventory-Name: '&7&l>&8&l> &8Auto Sell' #The name of the inventory when the player sells from a sign.
    Sign-Maker: '{SellChest}' #The line the player puts at the top to make a sign.
    Two-Factor-Auth-Options: #The options for the signs if the two factor auth option is on.
      Inventory-Name: '&7&l>&8&l> &8Two Factor Authentication' #The name of the inventory that opens.
      Accept: #The item for the accept button.
        Item: 'STAINED_GLASS_PANE:5'
        Name: '&a&lAccept'
        Lore:
          - '&7Click this option to sell all items.'
          - '&7&l(&c&l!&7&l) &cClosing this inventory will auto sell.'
      Info: #The item for the Info button.
        Item: 'STAINED_GLASS_PANE:7'
        Name: '&6&lInformation'
        Lore:
          - ''
          - '          &a<--- Sell the inventory'
          - '       &cDon''t sell the inventory --->'
          - ''
          - '&7&l(&c&l!&7&l) &cClosing this inventory will auto sell.'
      Deny: #The item for the deny button.
        Item: 'STAINED_GLASS_PANE:14'
        Name: '&c&lDeny'
        Lore:
          - '&7Click this option to get your items back.'
          - '&7&l(&c&l!&7&l) &cClosing this inventory will auto sell.'
    Lines: #When a sign is made what the lines will be.
      1: '&8[&7Auto-Sell&8]'
      2: 'Click here to sell'
      3: 'your items you'
      4: 'don''t want.'
  Black-List-Items: #Black listed items that can't be sold.
    - 'BEDROCK' #BedRock
    - 'SPONGE' #Sponge
  Black-List-Enchantments: { } #Use like the normal Black-List option if using it this.
  Enchantment-Cost: #The extra "Currency" each enchantment level gives to an item.
    #If you wish not to give extra make it like this "Enchantment-Cost: {}" and remove all enchantments.
    KNOCKBACK: #The enchantment which gives more "Currency"
      - 'Level:1, Cost:50' #The Level the enchantment is and the cost that level gives.
      - 'Level:2, Cost:135'
      - 'Level:3, Cost:200'
  #######################
  # Item:<ID:MD> - The item ID and Metadata. Metadata is optional.
  # Cost:<Number> - The amount of currency the player will get for selling it.
  # Currency:<XP_Level/XP_Total/<Custom Currency Name>> - The currency the player gets for selling it.
  # Example: - 'Item:311, Cost:4, Currency:Vault'
  #
  # Item Names can be found here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  #######################
  Item-Cost:
    - 'Item:OAK_LOG, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:WHITE_WOOL, Cost:0.0, Currency:Vault, Amount:1'
    - 'Item:OAK_LEAVES, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:OAK_SAPLING, Cost:0.0, Currency:Vault, Amount:1'
    - 'Item:STONE_BUTTON, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:OAK_PLANKS, Cost:0.0, Currency:Vault, Amount:1'
    - 'Item:ARROW, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_PICKAXE, Cost:650.0, Currency:Vault, Amount:1'
    - 'Item:COD, Cost:5.0, Currency:Vault, Amount:1'
    - 'Item:MINECART, Cost:23.0, Currency:Vault, Amount:1'
    - 'Item:LEATHER_CHESTPLATE, Cost:85.0, Currency:Vault, Amount:1'
    - 'Item:CHEST_MINECART, Cost:30.0, Currency:Vault, Amount:1'
    - 'Item:FEATHER, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_CHESTPLATE, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:MUSHROOM_STEW, Cost:4.0, Currency:Vault, Amount:1'
    - 'Item:BREAD, Cost:30.0, Currency:Vault, Amount:1'
    - 'Item:WATER, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:CRAFTING_TABLE, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:STONE_HOE, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:BROWN_MUSHROOM, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_HOE, Cost:400.0, Currency:Vault, Amount:1'
    - 'Item:WOODEN_SWORD, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:TORCH, Cost:4.0, Currency:Vault, Amount:1'
    - 'Item:GRASS_BLOCK, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:FURNACE_MINECART, Cost:32.0, Currency:Vault, Amount:1'
    - 'Item:SNOWBALL, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_APPLE, Cost:100.0, Currency:Vault, Amount:1'
    - 'Item:LEATHER_LEGGINGS, Cost:75.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_AXE, Cost:650.0, Currency:Vault, Amount:1'
    - 'Item:SLIME_BALL, Cost:50.0, Currency:Vault, Amount:1'
    - 'Item:OAK_FENCE, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:STONE_SHOVEL, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:BRICK, Cost:5.0, Currency:Vault, Amount:1'
    - 'Item:NOTE_BLOCK, Cost:36.0, Currency:Vault, Amount:1'
    - 'Item:IRON_AXE, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:COAL_ORE, Cost:15.0, Currency:Vault, Amount:1'
    - 'Item:CLAY_BALL, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:FISHING_ROD, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:IRON_HOE, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:MUSIC_DISC_13, Cost:100.0, Currency:Vault, Amount:1'
    - 'Item:IRON_PICKAXE, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:IRON_DOOR, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:BUCKET, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:POPPY, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:COOKED_PORKCHOP, Cost:7.0, Currency:Vault, Amount:1'
    - 'Item:GRAVEL, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:OAK_DOOR, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:CHAINMAIL_HELMET, Cost:40.0, Currency:Vault, Amount:1'
    - 'Item:IRON_CHESTPLATE, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_BLOCK, Cost:2000.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_HELMET, Cost:1000.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_HELMET, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:REDSTONE_TORCH, Cost:32.0, Currency:Vault, Amount:1'
    - 'Item:IRON_SHOVEL, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:FURNACE, Cost:8.0, Currency:Vault, Amount:1'
    - 'Item:IRON_SWORD, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:DISPENSER, Cost:58.0, Currency:Vault, Amount:1'
    - 'Item:WOODEN_AXE, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:WHEAT_SEEDS, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:PAINTING, Cost:25.0, Currency:Vault, Amount:1'
    - 'Item:OAK_PRESSURE_PLATE, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:REDSTONE_ORE, Cost:30.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_SHOVEL, Cost:210.0, Currency:Vault, Amount:1'
    - 'Item:WATER_BUCKET, Cost:40.0, Currency:Vault, Amount:1'
    - 'Item:BEDROCK, Cost:100.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_HOE, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:SAND, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_SWORD, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:STONE_AXE, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:BOOKSHELF, Cost:140.0, Currency:Vault, Amount:1'
    - 'Item:IRON_BLOCK, Cost:190.0, Currency:Vault, Amount:1'
    - 'Item:JACK_O_LANTERN, Cost:56.0, Currency:Vault, Amount:1'
    - 'Item:OAK_BOAT, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_CHESTPLATE, Cost:1750.0, Currency:Vault, Amount:1'
    - 'Item:REDSTONE_WIRE, Cost:30.0, Currency:Vault, Amount:1'
    - 'Item:RED_MUSHROOM, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:STRING, Cost:5.0, Currency:Vault, Amount:1'
    - 'Item:STONE_PRESSURE_PLATE, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:AIR, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:CACTUS, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:GUNPOWDER, Cost:20.0, Currency:Vault, Amount:1'
    - 'Item:RAIL, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:IRON_ORE, Cost:18.0, Currency:Vault, Amount:1'
    - 'Item:LEATHER_HELMET, Cost:52.0, Currency:Vault, Amount:1'
    - 'Item:STONE, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:EGG, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_ORE, Cost:200.0, Currency:Vault, Amount:1'
    - 'Item:WOODEN_HOE, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_LEGGINGS, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:CHAINMAIL_LEGGINGS, Cost:50.0, Currency:Vault, Amount:1'
    - 'Item:DANDELION, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:IRON_HELMET, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:OBSIDIAN, Cost:130.0, Currency:Vault, Amount:1'
    - 'Item:DIRT, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:LEATHER, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:LEATHER_BOOTS, Cost:42.0, Currency:Vault, Amount:1'
    - 'Item:LEVER, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:COBBLESTONE, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:CAKE, Cost:180.0, Currency:Vault, Amount:1'
    - 'Item:OAK_STAIRS, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:IRON_INGOT, Cost:0.0, Currency:Vault, Amount:1'
    - 'Item:GOLD_ORE, Cost:45.0, Currency:Vault, Amount:1'
    - 'Item:CARVED_PUMPKIN, Cost:50.0, Currency:Vault, Amount:1'
    - 'Item:RED_BED, Cost:68.0, Currency:Vault, Amount:1'
    - 'Item:CLOCK, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:IRON_LEGGINGS, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:SIGN, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:STONE_SLAB, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:WOODEN_PICKAXE, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:STONE_PICKAXE, Cost:4.0, Currency:Vault, Amount:1'
    - 'Item:CHAINMAIL_BOOTS, Cost:30.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_LEGGINGS, Cost:1500.0, Currency:Vault, Amount:1'
    - 'Item:COOKED_COD, Cost:7.0, Currency:Vault, Amount:1'
    - 'Item:SADDLE, Cost:100.0, Currency:Vault, Amount:1'
    - 'Item:COBBLESTONE_STAIRS, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:TNT, Cost:100.0, Currency:Vault, Amount:1'
    - 'Item:APPLE, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:WOODEN_SHOVEL, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:GOLD_INGOT, Cost:105.0, Currency:Vault, Amount:1'
    - 'Item:REPEATER, Cost:110.0, Currency:Vault, Amount:1'
    - 'Item:FARMLAND, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:CLAY, Cost:12.0, Currency:Vault, Amount:1'
    - 'Item:GOLD_BLOCK, Cost:450.0, Currency:Vault, Amount:1'
    - 'Item:STICK, Cost:0.0, Currency:Vault, Amount:1'
    - 'Item:PAPER, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:BRICKS, Cost:21.0, Currency:Vault, Amount:1'
    - 'Item:LAVA, Cost:1.0, Currency:Vault, Amount:1'
    - 'Item:CHEST, Cost:4.0, Currency:Vault, Amount:1'
    - 'Item:SANDSTONE, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_PICKAXE, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:COMPASS, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:SUGAR_CANE, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_SWORD, Cost:420.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_BOOTS, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:STONE_SWORD, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:COAL, Cost:15.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_AXE, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:BONE, Cost:2.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND, Cost:200.0, Currency:Vault, Amount:1'
    - 'Item:GLASS, Cost:3.0, Currency:Vault, Amount:1'
    - 'Item:GOLDEN_SHOVEL, Cost:6.0, Currency:Vault, Amount:1'
    - 'Item:LAPIS_BLOCK, Cost:950.0, Currency:Vault, Amount:1'
    - 'Item:LAVA_BUCKET, Cost:40.0, Currency:Vault, Amount:1'
    - 'Item:WHEAT, Cost:9.0, Currency:Vault, Amount:1'
    - 'Item:LADDER, Cost:0.0, Currency:Vault, Amount:1'
    - 'Item:BOWL, Cost:0.0, Currency:Vault, Amount:1'
    - 'Item:CHAINMAIL_CHESTPLATE, Cost:40.0, Currency:Vault, Amount:1'
    - 'Item:DIAMOND_BOOTS, Cost:850.0, Currency:Vault, Amount:1'
    - 'Item:LAPIS_ORE, Cost:100.0, Currency:Vault, Amount:1'
    - 'Item:MILK_BUCKET, Cost:40.0, Currency:Vault, Amount:1'
    - 'Item:REDSTONE, Cost:32.0, Currency:Vault, Amount:1'
    - 'Item:MUSIC_DISC_CAT, Cost:100.0, Currency:Vault, Amount:1'
    - 'Item:INK_SAC, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:GLOWSTONE_DUST, Cost:10.0, Currency:Vault, Amount:1'
    - 'Item:BOOK, Cost:45.0, Currency:Vault, Amount:1'
    - 'Item:BOW, Cost:15.0, Currency:Vault, Amount:1'
    - 'Item:IRON_BOOTS, Cost:22.0, Currency:Vault, Amount:1'
    - 'Item:SUGAR, Cost:10.0, Currency:Vault, Amount:1'