name: EpicSellChest
main: "${group}.EpicSellChest"
version: ${version}
api-version: 1.13
description: ${description}

authors:
  - BadBones69
  - RyderBelserion

softdepend: [Vault, NoCheatPlus, ShopGUIPlus]

commands:
  sellchest:
    description: Sell all items in a chest.
    aliases: [sc]